# Generated by Django 6.1.1 on 2026-09-07 21:11

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='ID')),
                ('oracle_id', models.CharField(db_index=True, max_length=64, verbose_name='Oracle ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('normalized_name', models.CharField(db_index=True, max_length=255)),
                ('mana_cost', models.CharField(blank=True, max_length=128, null=True)),
                ('cmc', models.FloatField(default=0.0, verbose_name='CMC')),
                ('type_line', models.CharField(blank=True, max_length=255, null=True)),
                ('oracle_text', models.TextField(blank=True, null=True)),
                ('colors', models.JSONField(default=list)),
                ('color_identity', models.JSONField(default=list)),
                ('image_uri', models.URLField(blank=True, max_length=512, null=True, verbose_name='Image URI')),
                ('legalities', models.JSONField(default=dict)),
                ('is_land', models.BooleanField(db_index=True, default=False)),
                ('is_basic_land', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CardLookup',
            fields=[
                ('lookup_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('canonical_name', models.CharField(db_index=True, max_length=255)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Resolution weight used to break ties when multiple cards share an alias or name (higher values take precedence during card resolution).')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lookups', to='core.card')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('format', models.CharField(choices=[('standard', 'Standard'), ('pioneer', 'Pioneer'), ('pauper', 'Pauper'), ('modern', 'Modern'), ('premodern', 'Premodern'), ('legacy', 'Legacy'), ('vintage', 'Vintage')], max_length=32)),
                ('event_type', models.CharField(max_length=32)),
                ('date', models.DateField(db_index=True)),
                ('uri', models.URLField(blank=True, max_length=512, null=True, verbose_name='URI')),
                ('deck_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', 'id'],
                'indexes': [models.Index(fields=['format', '-date'], name='core_tourna_format_1bfd4d_idx'), models.Index(fields=['event_type', '-date'], name='core_tourna_event_t_9324d0_idx'), models.Index(fields=['format', 'event_type', '-date'], name='core_tourna_format_394d66_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('format__in', ['standard', 'pioneer', 'pauper', 'modern', 'premodern', 'legacy', 'vintage'])), name='core_tournament_format_valid')],
            },
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('standard', 'Standard'), ('pioneer', 'Pioneer'), ('pauper', 'Pauper'), ('modern', 'Modern'), ('premodern', 'Premodern'), ('legacy', 'Legacy'), ('vintage', 'Vintage')], max_length=32)),
                ('player', models.CharField(max_length=255)),
                ('player_lower', models.CharField(db_index=True, max_length=255)),
                ('result', models.CharField(max_length=64)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('is_top8', models.BooleanField(default=False)),
                ('is_5_0', models.BooleanField(default=False, verbose_name='is 5-0')),
                ('archetype', models.CharField(max_length=128)),
                ('archetype_slug', models.CharField(db_index=True, max_length=128)),
                ('is_auto_classified', models.BooleanField(default=False, help_text="Indicates whether this deck was assigned an archetype via heuristic fallback (such as color + posture) because it did not match any explicit archetype rules in the format's YAML definition.")),
                ('colors', models.CharField(max_length=10)),
                ('color_name', models.CharField(max_length=32)),
                ('mainboard', models.JSONField(default=list)),
                ('sideboard', models.JSONField(default=list)),
                ('anchor_uri', models.URLField(blank=True, max_length=512, null=True, verbose_name='Anchor URI')),
                ('is_legal_today', models.BooleanField(default=True)),
                ('illegal_cards', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to='core.tournament')),
            ],
            options={
                'ordering': ['-tournament__date', 'rank', 'id'],
                'indexes': [models.Index(fields=['format', 'archetype_slug'], name='core_deck_format_73f0cd_idx'), models.Index(fields=['format', 'archetype_slug', 'tournament'], name='core_deck_format_fac755_idx'), models.Index(fields=['format', 'tournament'], name='core_deck_format_8ccdae_idx'), models.Index(fields=['format', 'is_top8'], name='core_deck_format_2c8e09_idx'), models.Index(fields=['format', 'is_top8', 'tournament'], name='core_deck_format_4cca66_idx'), models.Index(fields=['format', 'is_5_0'], name='core_deck_format_79a477_idx'), models.Index(fields=['format', 'is_5_0', 'tournament'], name='core_deck_format_c800db_idx'), models.Index(fields=['format', 'colors'], name='core_deck_format_a316b4_idx'), models.Index(fields=['player_lower', 'format'], name='core_deck_player__be11e4_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('format__in', ['standard', 'pioneer', 'pauper', 'modern', 'premodern', 'legacy', 'vintage'])), name='core_deck_format_valid')],
            },
        ),
    ]
