# Generated by Django 6.1.1 on 2026-09-14

from django.db import migrations
from django.db import models
from django.utils.text import slugify


def populate_card_slugs(apps, schema_editor):
    Card = apps.get_model("core", "Card")
    used_slugs = set()
    for card in Card.objects.all().iterator():
        base_slug = slugify(card.name or "") or "card"
        candidate = base_slug
        counter = 1
        while candidate in used_slugs:
            candidate = f"{base_slug}-{counter}"
            counter += 1
        used_slugs.add(candidate)
        card.slug = candidate
        card.save(update_fields=["slug"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="printings",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="card",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(
            populate_card_slugs, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="card",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
