# Generated by Django 6.1.1 on 2026-09-16 06:09

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_card_slug_and_printings"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="player_count",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
