# Generated by Django 6.1.1 on 2026-09-16 20:48

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_tournament_player_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="card_faces",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
