# Generated by Django 6.1.1 on 2026-09-17 04:53

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_card_card_faces"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_name", models.CharField(max_length=64)),
                ("round_slug", models.CharField(db_index=True, max_length=64)),
                ("player1", models.CharField(max_length=255)),
                ("player2", models.CharField(max_length=255)),
                ("player1_wins", models.IntegerField(default=0)),
                ("player2_wins", models.IntegerField(default=0)),
                ("draws", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player1_deck",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matches_as_p1",
                        to="core.deck",
                    ),
                ),
                (
                    "player2_deck",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matches_as_p2",
                        to="core.deck",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="core.tournament",
                    ),
                ),
            ],
            options={
                "verbose_name": "Match",
                "verbose_name_plural": "Matches",
                "ordering": ["-tournament__date", "round_slug", "id"],
                "indexes": [
                    models.Index(
                        fields=["tournament", "round_slug"],
                        name="core_match_tournam_3d50c0_idx",
                    )
                ],
            },
        ),
    ]
