# Generated by Django 6.1.1 on 2026-09-20 03:43

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_match"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="source",
            field=models.CharField(
                choices=[("mtgo", "MTGO"), ("ldcp", "LDCP")],
                db_index=True,
                default="mtgo",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["tournament", "source"], name="core_match_tournam_25c52e_idx"
            ),
        ),
    ]
