# Generated by Django 6.1.1 on 2026-09-26 23:33

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_match_source_match_core_match_tournam_25c52e_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="source",
            field=models.CharField(
                choices=[("mtgo", "MTGO"), ("ldcp", "LDCP"), ("vmc", "VMC")],
                db_index=True,
                default="mtgo",
                max_length=16,
            ),
        ),
    ]
