# Generated by Django 6.1.1 on 2026-09-27 05:53

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_match_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="deck",
            name="draws",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deck",
            name="losses",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deck",
            name="omwp",
            field=models.FloatField(blank=True, null=True, verbose_name="OMWP"),
        ),
        migrations.AddField(
            model_name="deck",
            name="points",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deck",
            name="wins",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="community_sheet_id",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Community Sheet ID"
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="standings",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
