# Generated by Django 6.1.1 on 2026-09-30 18:16

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_deck_draws_deck_losses_deck_omwp_deck_points_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deck",
            name="classification_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rule", "Deterministic Rule"),
                    ("knn", "TF-IDF kNN Closeness"),
                    ("fallback", "Tactical Posture Fallback"),
                ],
                db_index=True,
                default=None,
                help_text="Method used to classify this deck: 'rule' (matched explicit rule), 'knn' (matched via TF-IDF kNN closeness to a rule-classified deck), or 'fallback' (heuristic tactical posture + color).",
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="deck",
            index=models.Index(
                fields=["format", "classification_method"],
                name="core_deck_format_f9b9e1_idx",
            ),
        ),
    ]
